### ISSUE TITLE
Problem with module installation

### ISSUE THREAD

**Issue by fefed22** [PrestaShop/autoupgrade#102]
/Applications/MAMP/htdocs/presta16120/src/Core/Addon/Theme/ThemeManager.php line 290 - PrestaShopException: Cannot install module ps_customtext. Unfortunately, the module did not return additional details.

**Comment by Quetzacoalt91** [comment]
Hi,

This issue will be fixed with https://github.com/PrestaShop/ps_customtext/pull/13
We have a conflict between the 1.6 (blockcmsinfo) and 1.7 modules which shares the sames database tables but not the exact structure anymore.

**Comment by Quetzacoalt91** [comment]
The PR has been merged, please wait for the release of PS 1.7.4.2 before trying again.

Thank you!
