### ISSUE TITLE
Some strange behaviour while upgrading from 1.7.3.4 to 1.7.4.0 with 1-Click upgrade version 4.0.0.beta-3

### ISSUE THREAD

**Issue by litebito** [PrestaShop/autoupgrade#104]
installation details : 
- on a shared hosting server, 
- with DirectAdmin panel
- upgrading from 1.7.3.4 to 1.7.4.0
- 1-click upgrade module : 4.0.0.beta3

Behaviour 1: downloaded version renamed 1.7.4.0 renamed to a local archive 1.7.2.5 :+1: 
```
Starting upgrade...
Downloaded archive will come from https://download.prestashop.com/download/releases/prestashop_1.7.4.0.zip
MD5 hash will be checked against 215e2af1db2683e93f1524d9cc1d9b59
[DEV] ajax request : download
Downloading from https://download.prestashop.com/download/releases/prestashop_1.7.4.0.zip
File will be saved in /home/xxx/public_html/shop/admin2shop/autoupgrade/download/prestashop_1.7.2.5.zip
Download directory has been emptied
Download complete.
```

Behaviour 2 : some errors at the end, although the upgrade seems successful. It looks as there is an issue with directory confusion:

```
/home/xxxxx/public_html/shop/admin2shop/autoupgrade/download/prestashop_1.7.2.5.zip removed
/home/xxxxx/public_html/shop/admin2shop/autoupgrade/latest removed
[INTERNAL] /home/xxxxx/public_html/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 362 - file_exists(): open_basedir restriction in effect. File(/home/yyyy/domains/composer.json) is not within the allowed path(s): (/home/xxxxx/:/home/yyyy/domains/include/:/etc/pki/tls/certs:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/)
[INTERNAL] /home/xxxxx/public_html/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 362 - file_exists(): open_basedir restriction in effect. File(/home/yyyy/composer.json) is not within the allowed path(s): (/home/xxxxx/:/home/yyyy/domains/include/:/etc/pki/tls/certs:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/)
[INTERNAL] /home/xxxxx/public_html/shop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 362 - file_exists(): open_basedir restriction in effect. File(/home/composer.json) is not within the allowed path(s): (/home/xxxxx/:/home/yyyy/domains/include/:/etc/pki/tls/certs:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php55/lib/php/)
End of process
```

**Comment by Quetzacoalt91** [comment]
## Behavior 1 

Interesting, this may come from a previous upgrade you made and the configuration has not been emptied. Is it the first upgrade you do on this shop?

## Behavior 2

This issue is related to the core, not the upgrade itself. Because we don't provide the file `composer.json` in our releases, the kernel may try to find it at several locations. Some server configuration prevent the look of this file in unexpected folders, throwing this error.
However, it does not prevent the upgrade or the core to work properly, you can ignore them.

**Comment by litebito** [comment]
regarding Behaviour 1
yes indeed, over the last few months, I had to do a number of manual upgrades, because the 1-Click upgrade fails every change of "X" in 1.7.X.y
1.7.2.5 is one of the upgrades which I had to do manually, but after that I did a few other upgrades, so it must be some variable left unclean after one of the upgrades.

**Comment by Quetzacoalt91** [comment]
The issue in behavior n°2 should be fixed with https://github.com/PrestaShop/PrestaShop/pull/9345
