### ISSUE TITLE
Autoupgrade 1.6.8 not working on Prestashop 1.6.1.17

### ISSUE THREAD

**Issue by iraniamoran** [PrestaShop/autoupgrade#107]
Describe the bug
Made the following test with the module:

    Upgrade by chanel: Local File

Upgrade environment:

    Version you started from: 1.6.1.17
    Version you upgrade to: 1.6.1.19
    Way of upgrade: Web
    Step concerned: unzip
    
Displayed log:
No displayed logs
No displayed PHP errors

Expected behavior:
Shows logs and upgrading steps while upgrading prestashop. 
I Have tried with other variants (Main and secondary...) and do not perform the first step of the upgrade process, the  module is not started the upgrade. (Last January when made an upgrade with the older version and it worked perfectly.)

Module Version 1.6.8

**Comment by Quetzacoalt91** [comment]
Hi @iraniamoran,

Could you please take some time to test the version v4.0.0-beta available in the releases page? https://github.com/PrestaShop/autoupgrade/releases

The versions on the marketplace aren't able to to display the error messages on the screen, but you should be luckier with the new one. :)

**Comment by Quetzacoalt91** [comment]
We released the version 4.0, please try again with this one and let us know if the issue still occurs.

In the meantime, I close this issue.
