### ISSUE TITLE
error when trying to update from ps1.7.4.1 to ps 1.7.4.2

### ISSUE THREAD

**Issue by aixos** [PrestaShop/autoupgrade#115]
error when trying to update from ps1.7.4.1 to ps 1.7.4.2
autoupgrade-v4.0.0-beta.5

Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)

Thanks

**Comment by eternoendless** [comment]
Hi @aixos 

Did you enable the file info extension?

**Comment by Quetzacoalt91** [comment]
On what step did you encounter this issue?

**Comment by Quetzacoalt91** [comment]
BTW, fileinfo is a mandatory PHP extension to run PrestaShop, @aixos shouldn't be able to upgrade your shop if he didn't enable it.

**Comment by aixos** [comment]
Ok . the hosting have php_fileinfo, run ok with autoupgrade-v4.0.0 estable
thanks

**Comment by Quetzacoalt91** [comment]
Hi @aixos,

If the upgrade went well with the stable version, can we close this issue?

**Comment by aixos** [comment]
sorry
Yes, with the stable version works fine
you can close this thread
thank so  much

**Comment by Quetzacoalt91** [comment]
Thanks for your feedback. :)
