### ISSUE TITLE
Not installed beta 5 on module page

### ISSUE THREAD

**Issue by tuhingr** [PrestaShop/autoupgrade#118]
I tried to install zip package via module page. Its continue installing but not complete.
how to install via FTP or File manager? please help!

**Comment by PierreRambaud** [comment]
As I know, it's currently not possible to install modules via ftp or file manager. Do you have some access to php logs or something?
Regards

**Comment by tuhingr** [comment]
Server information Linux #1 SMP Wed May 2 07:43:19 EDT 2018 x86_64

Server software version: Apache

PHP version: 5.6.37

Memory limit: 512M

Max execution time: 0

Upload Max File size: 1G

**Comment by Quetzacoalt91** [comment]
Hi @tuhingr,

The version v4.0 is now available on the marketplace. You can install this version directly from the module page without having to upload a zip file. :)

Good luck with the upgrade!
