### ISSUE TITLE
1.6.1.4 -> 1.7.4.2 failing at Database Upgrading (4.0.0 version)

### ISSUE THREAD

**Issue by dadrcheng** [PrestaShop/autoupgrade#121]
I tried several times using 4.0.0 version to upgrade.  But it keeps failing for me at upgrading the database.  It looks to be failing starting at product attributes tables.

Your current PrestaShop version: 1.6.1.4
Latest official version for major channel.: 1.7.4 stable - (1.7.4.2)

**Comment by Quetzacoalt91** [comment]
Hi @dadrcheng,

Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`

**Comment by Quetzacoalt91** [comment]
Hi,

Without further details, I absolutely can't provide any help.
Feel free to answer on this issue once you got the logs.

Regards
