### ISSUE TITLE
Error at the end of upgrade process using 1-click 4.0.0 (last version)

### ISSUE THREAD

**Issue by Ingematic** [PrestaShop/autoupgrade#125]
Hi,
I'm trying to upgrade version 1.7.3.3 to 1.7.4.2 using 1-click upgrade latest version 4.0.0 but at the end of the process the following error is returned with a red color:

**Errori**
_[INTERNAL] /var/www/vhosts/NOMESITO.com/httpdocs/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 48 - Interface 'Symfony\Component\HttpKernel\RebootableInterface' not found_

I have try others upgrade from 1.7.3.1 1.7.3.0 to 1.7.4.0 or 1.7.4.1 or 1.7.4.2 with the same error.
Thank you for assistence.

**Activity Register**
**The first box stop with this lines:**
. . . .
311 files left to upgrade.
All files upgraded. Now upgrading database...

**The second box show:**
. . . .
Copied /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/RebootableInterface.php.
. . . . .
Copied /webservice/index.php.
[INTERNAL] /var/www/vhosts/NOMESITO.com/httpdocs/vendor/composer/autoload_real.php line 61 - require(/var/www/vhosts/NOMESITO.com/httpdocs/vendor/composer/../symfony/polyfill-php55/bootstrap.php): failed to open stream: No such file or directory
[INTERNAL] /var/www/vhosts/NOMESITO.com/httpdocs/vendor/composer/autoload_real.php line 61 - require(/var/www/vhosts/NOMESITO.com/httpdocs/vendor/composer/../symfony/polyfill-php54/bootstrap.php): failed to open stream: No such file or directory
[INTERNAL] /var/www/vhosts/NOMESITO.com/httpdocs/config/autoload.php line 33 - require(/var/www/vhosts/NOMESITO.com/httpdocs/config/../app/autoload.php): failed to open stream: No such file or directory
Migrating old setting file...
parameters file already exists!
Finished...
[INTERNAL] /var/www/vhosts/NOMESITO.com/httpdocs/modules/autoupgrade/vendor/composer/ClassLoader.php line 444 - include(/var/www/vhosts/NOMESITO.com/httpdocs/vendor/composer/../prestashop/smarty/Smarty.class.php): failed to open stream: No such file or directory
[INTERNAL] /var/www/vhosts/NOMESITO.com/httpdocs/vendor/prestashop/smarty/Smarty.class.php line 1680 - include(/var/www/vhosts/NOMESITO.com/httpdocs/vendor/prestashop/smarty/sysplugins/smarty_resource_custom.php): failed to open stream: No such file or directory
[OK] SQL 1.7.4.0 SET SESSION sql_mode = ''
[OK] SQL 1.7.4.0 SET NAMES 'utf8'
[OK] SQL 1.7.4.0 ALTER TABLE `pshop_order_detail` DROP KEY product_id, ADD KEY product_id (product_id, product_attribute_id)
[OK] SQL 1.7.4.0 INSERT IGNORE INTO `pshop_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES (NULL, 'actionAdministrationPageForm', 'Manage Administration Page form fields', 'This hook adds, update or remove fields of the Administration Page form', '1'), (NULL, 'actionAdministrationPageFormSave', 'Processing Administration page form', 'This hook is called when the Administration Page form is processed', '1'), (NULL, 'actionPerformancePageForm', 'Manage Performance Page form fields', 'This hook adds, update or remove fields of the Performance Page form', '1'), (NULL, 'actionPerformancePageFormSave', 'Processing Performance page form', 'This hook is called when the Performance Page form is processed', '1'), (NULL, 'actionMaintenancePageForm', 'Manage Maintenance Page form fields', 'This hook adds, update or remove fields of the Maintenance Page form', '1'), (NULL, 'actionMaintenancePageFormSave', 'Processing Maintenance page form', 'This hook is called when the Maintenance Page form is processed', '1'), (NULL, 'displayAdminEndContent', 'Administration end of content', 'This hook is displayed at the end of the main content, before the footer', '1')
[OK] PHP 1.7.4.0 : /* PHP:ps_1740_update_module_tabs(); */
[OK] SQL 1.7.4.1 SET SESSION sql_mode = ''
[OK] SQL 1.7.4.1 SET NAMES 'utf8'
[OK] SQL 1.7.4.1 ALTER TABLE `pshop_cart_rule` ADD KEY `date_from` (`date_from`), ADD KEY `date_to` (`date_to`)
[OK] SQL 1.7.4.2 SET SESSION sql_mode = ''
[OK] SQL 1.7.4.2 SET NAMES 'utf8'
[OK] SQL 1.7.4.2 UPDATE `pshop_employee` SET `bo_css` = "theme.css"

**Upgrade environment:**
 - Version you started from: [e.g. 1.7.3.3]
 - Version you upgrade to: [e.g. 1.7.4.2]
 - Way of upgrade: Directory / Archive / Last version web
 - Step concerned: [error at the end] 

**Displayed log**
[log.txt](https://github.com/PrestaShop/autoupgrade/files/2273661/log.txt)

**Screenshots**
No

**Server (please complete the following information):**
 - Web Server: [Apache / Nginx]
 - PHP Version: [e.g. 7.0.31]
 - Module Version [4.0.0]

**Comment by Quetzacoalt91** [comment]
Thanks for the full report. This could be related to a similar issue: #82

**Comment by Ingematic** [comment]
Il suo messaggio è stato correttamente recapitato al Supporto OnLine.
Risponderemo al più presto.

Grazie per averci contattato
Staff - INGEMATIC Web Management

**Comment by Ingematic** [comment]
Thank you immediately read the references provided.
I normally always clear the cache before proceeding with the update, from:
Backoffice -> Advanced parameters -> Performance -> Clear cache
and also delete the folder:
/ Root / app / cache /
Is there an alternative or additional procedure that I should follow?
Regards

**Comment by Ingematic** [comment]
Thank you

**Comment by Ingematic** [comment]
Hi Thomas,
i have repeted the upgrade after disabled all type of cache on server (ex Opcache and Google pagespeed), but i have the same error.
I don't now.
Thanks

**Comment by Mushr0000m** [comment]
Same problem here on local MAMP with PHP 7.1.13, no cache or accelaration extensions. It download then crash.

**Comment by Quetzacoalt91** [comment]
With https://github.com/PrestaShop/autoupgrade/pull/306, all cache folders are now emptied before running freshly copied classes.
The first tests show that upgrade can now be done without having conflicts between the cache and the actual classes, so I close this issue. If the problem still occur on your side after the release of v4.8.0 of the module, feel free to reopen this issue.

Regards
