### ISSUE TITLE
CoreUpgrader16.php calling Tools::passwdGen(32) in line 67 when Tools does not exist

### ISSUE THREAD

**Issue by jt3204** [PrestaShop/autoupgrade#140]
`public_html/store/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader16.php line 67 - Class 'PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\Tools' not found`
This critical (fail) error is what I receive when attempting to upgrade my store. On inspection, there is no tools.php file in the CoreUpgrader folder.

Line 67 is being called as Line 63 is returning false due to another error:
`[INTERNAL] /public_html/store/classes/Cookie.php line 79 - Use of undefined constant _RIJNDAEL_KEY_ - assumed '_RIJNDAEL_KEY_'`
`[INTERNAL] /public_html/store/classes/Cookie.php line 79 - Use of undefined constant _RIJNDAEL_IV_ - assumed '_RIJNDAEL_IV_'`
`[INTERNAL] /public_html/store/classes/Rijndael.php line 91 - openssl_decrypt(): IV passed is only 7 bytes long, cipher expects an IV of precisely 16 bytes, padding with \0"`

However I do not believe that to be the fault of this module.

**Comment by Quetzacoalt91** [comment]
Thank you for the report. There is actually an issue on the module, which is the fatal error.

A fix will be provided for the next version: https://github.com/PrestaShop/autoupgrade/pull/141.

**Comment by Quetzacoalt91** [comment]
As the related PR is merged, I'm closing your issue. The fix will be available in the version 4.1.0 of the module.
