### ISSUE TITLE
After upload module with prestashop back office - error 500 comes up for all admin panel and I cant enter to backoffice

### ISSUE THREAD

**Issue by Tomskor** [PrestaShop/autoupgrade#146]
When I trying to upgrade autoupgrade module from back office with UPLOAD MODULE what I downloaded from github this error shows up: 

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

**Upgrade environment (please complete the following information):**
 - Version you started from: 4.1 beta 2
 - Version you upgrade to: 4.1 final 
 - Way of upgrade: Backoffice

**Displayed log**

Dont have any acces

Any idea what fix it?

**Comment by Tomskor** [comment]
![asd](https://user-images.githubusercontent.com/42567245/44580391-10980300-a79a-11e8-8264-695a8d23e13a.jpg)
After dev mode on this shows up

**Comment by Quetzacoalt91** [comment]
Can you please reach the folder `modules` of your shop and remove the folder `autoupgrade`? You may have to do it via FTP.

Once done, try again to reupload the module and let us know if it works again.

**Comment by Quetzacoalt91** [comment]
Duplicates https://github.com/PrestaShop/PrestaShop/issues/10118.

Closing this one.

**Comment by Ingematic** [comment]
Hi,
i have find the "Error 500 Internal Server Error" in the admin section, after uninstall the module 1-click upgrade ver 4.0.0
I have version PS 1.7.4.2
If i rename the /root/modules/ps_facetedsearch in other name, the error 500 non compare.
After if i restore the name of module ps_facetedsearch then i have the error 500.
Have you any idea?
Thank you
Michele

**Comment by Quetzacoalt91** [comment]
Did you mean that the error disappear as soon as `ps_facetedsearch` is removed?

If yes, you should download the latest version of this module, it contains some change which should prevent this error to occur.

**Comment by Ingematic** [comment]
Il suo messaggio è stato correttamente recapitato al Supporto OnLine.
Risponderemo al più presto.

Grazie per averci contattato
Staff - INGEMATIC Web Management

**Comment by Ingematic** [comment]
Hi,
yes the error 500 disappear if i rename ps_facetedsearch in /root/modules/
but i have cheched, the version of this module is the last available.
Thank you for support

**Comment by Ingematic** [comment]
Hi, have you anu news for this problem?
Many thanks
