### ISSUE TITLE
PrestaShop requirements are not satisfied - but nothing to do...

### ISSUE THREAD

**Issue by FigoVik** [PrestaShop/autoupgrade#149]
**Describe the bug**

Looks like every necessary requirements are good, but something is missing for a module, if I click on it see details, drop me on informations page and show:

Necessary parameters: please fix the next error(s)
optional parameters (OK) 

--
but not have any list what should need to fix.

Please advise

**Upgrade environment (please complete the following information):**
 - Version you started from: [e.g. 1.7.3.0]
 - Version you upgrade to: [e.g. 1.7.4.2]
 - Way of upgrade: Web
 - Step concerned: nothing

**Server (please complete the following information):**
 - Web Server: Apache 2.4.24, dEbian 9.5
 - mariaDB 10.1  (innoDB engine)
 - PHP Version: [e.g. 7.0.3.0] php-fpm
 - Module Version [e.g. 4.1]
 - unlimited ram, SSD, dedicated 2way server

**Comment by Quetzacoalt91** [comment]
Hi,

There is an issue on the core side, which does not display some issues waiting to be fixed. You can find a pull-request about that here: https://github.com/PrestaShop/PrestaShop/pull/9407.
The specific commit which always displays the error is https://github.com/PrestaShop/PrestaShop/pull/9407/commits/bdd7bb49db96ba40d79003482b29fa8bcaf9316b

If you want to force the update even if the PrestaShop are not fine, you can do this by applying the following changes on the module: https://github.com/PrestaShop/autoupgrade/compare/master...Quetzacoalt91:non-blocking-ps-check?expand=1.

**Comment by Quetzacoalt91** [comment]
The version 4.2.0 currently in beta will handle that issue. You are now able to ignore this step, although this may bring issue during the upgrade process.

Feel free to try it on https://github.com/PrestaShop/autoupgrade/releases.

Fixed by #167.
Regards
