### ISSUE TITLE
[Question] Can upgrade from 1.6 to 1.7?

### ISSUE THREAD

**Issue by nyenye** [PrestaShop/autoupgrade#151]
I was wondering if this module could be used to upgrade a Prestashop with version 1.6 to the newest 1.7 version.

Thanks in advance for any insight.
Cheers.

**Comment by Quetzacoalt91** [comment]
Hello,

It does, this module is one of the solution given to keep PrestaShop up to date: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/#1-click-upgrade-module.

Note that even if it works, this is probably not the best solution for your case as you want to switch from PS 1.6 to 1.7. Although the upgrade process is the same, you won't be able able to keep everything from your current shop (for instance, the theme). Here again, we advise you to have a look on the documentation: https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/#impact-on-existing-data-1

Kind regards

**Comment by nyenye** [comment]
Oh thanks! And sorry for the late reply. The thing is the theme will be changed too, so my main concern lies with catalogue and orders, prices, and such. For modules, we'll use what comes with the theme, and upgrade the free/mandatory ones.

Can I rest easy? Of course we'll make a backup first just in case.

**Comment by Quetzacoalt91** [comment]
Indeed, always make a backup before starting an upgrade. You will be glad to find it if something goes wrong.

Your data should be fine with the upgrade. Previous feedbacks bring us some issue about module compatibility. Even if it succeed, you may have some errors while browsing the shop or the administration panel. If it occurs, look at the server logs to check if it's related to an old module.

**Comment by nyenye** [comment]
Thanks again! Closing the issue.
