### ISSUE TITLE
"Update prestashop now" button doesn't appears

### ISSUE THREAD

**Issue by Joslk** [PrestaShop/autoupgrade#177]
Hi, im triying to update drom 1.6.0.11 to 1.7.4.3 and i have all checked but "Update prestashop now" button doesn't appears, I also try that: "https://github.com/PrestaShop/autoupgrade/compare/master...Quetzacoalt91:non-blocking-ps-check?expand=1"

But nothing happens.

I have module version 4.3.0

Thanks.

<img width="1749" alt="captura de pantalla 2018-10-13 13 26 03" src="https://user-images.githubusercontent.com/35629284/46904911-05d13300-ceec-11e8-8f3b-7d5cacb7f701.png">

**Comment by Joslk** [comment]
I found the problem, a problem with translation "Update prestashop now" was empty and the button appears very small :S
<img width="1749" alt="captura de pantalla 2018-10-13 13 26 03" src="https://user-images.githubusercontent.com/35629284/46918784-9a17c480-cfd6-11e8-8752-7427a03ec688.png">

**Comment by Quetzacoalt91** [comment]
Hmm, that's weird, the text is properly displayed on my side:

![capture du 2018-10-15 10-32-37](https://user-images.githubusercontent.com/6768917/46943286-3ab5c500-d067-11e8-849a-327cb5911bcc.png)

Your translation file is probably obsolete. If the issue still occurs, could you try removing the module from the modules folder (`modules/autoupgrade`)? If you redownload the module from the marketplace, you might get the translated strings properly.

**Comment by Quetzacoalt91** [comment]
For your information, I'm closing this issue as there is no change to bring to the project.

Thanks!
