### ISSUE TITLE
The refresh button is not displayed when we use a local archive

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/autoupgrade#185]
**Describe the bug**

In the configuration page, when we use the local archive option, the button "Refresh the page" is not displayed after Clicking "Save".
We should refresh the page manually, so this button is displayed.
![image](https://user-images.githubusercontent.com/16067358/47785478-2af5dc00-dd09-11e8-8b65-db349a9b8186.png)

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.7.4.3 / 1.6.1.22
 - Version you upgrade to: 1.7.4.4
 - Way of upgrade: Local archive

**Expected behavior**
When we click on "save" => the button "Refresh the page" should be automatically displayed.

**Screenshots**
https://drive.google.com/file/d/1mJZwWZVm2WRNWDnXJQ8fCS_K_R4Powbn/view

**Server (please complete the following information):**
 - Web Server: Apache
 - PHP Version: 1.7.4.3 / 1.6.1.22
 - Module Version: 4.4.0

**Comment by jolelievre** [comment]
Additionally, the javascript should manage the autoreload automatically.

Hint:
the problem lies in the `afterUpdateConfig` when calling `showConfigResult` with a type (undefined), this check doesn't work:

```
if (type === null) {
    type = "conf";
  }
```

**Comment by Quetzacoalt91** [comment]
Fixed by #187. Thanks.
