### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by MathiasReker** [PrestaShop/autoupgrade#199]
I see a lot of errors here when validation the module. Maybe some of them should be fixed?
Link: https://validator.prestashop.com

Report:
[autoupgrade_validation_20181221.txt](https://github.com/PrestaShop/autoupgrade/files/2702592/autoupgrade_validation_20181221.txt)

**Comment by Quetzacoalt91** [comment]
Hoy,

Be careful about these errors. The validator main advise to use the core methods, while during the upgrade we CANNOT rely on it. The core is actually being upgraded, and its behavior may change between two calls. Using its methods is likely to make the process failing.
