### ISSUE TITLE
Error in upgrade to PrestaShop 1.7.5.0 to 1.7.5.1

### ISSUE THREAD

**Issue by joseabellan84** [PrestaShop/autoupgrade#287]
**Describe the bug**
Error in the upgrade to PrestaShop 1.7.5.0 to 1.7.5.1

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.7.5.0
 - Version you upgrade to: 1.7.5.1
 - Way of upgrade: Web

**Displayed log**
Updating database schema...

06:27:07 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign". Message: "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it." ["exception" => Doctrine\DBAL\DBALException { …},"command" => "prestashop:schema:update-without-foreign","message" => "Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it."]

In AbstractPlatform.php line 423:

Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform

may not support it.

prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]

**Server (please complete the following information):**
 - Web Server: Apache/2
 - PHP Version: 7.2.15
 - Module Version: 4.6.0

**Comment by Quetzacoalt91** [comment]
Hi there,

Thanks for your report.
This is not the first time we see this issue being reported. Please have a look at #87 to solve this specific issue.
I'm closing as we currently deal with a duplicate.

Regards
