### ISSUE TITLE
Some upgrade scripts on PS 1.7.6.0 require the kernel to be enabled

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/autoupgrade#298]
**Describe the bug**
AppKernel is not instanciated when upgrading the database.

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.6.1.23
 - Version you upgrade to: 1.7.6.0
 - Way of upgrade: Web
 - Step concerned: Upgrade DB

**Displayed log**
```
[2019-04-18 17:52:42] [INTERNAL] /var/www/html/admin-dev/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 53 - Error: Call to a member function get() on null
#0 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang()
#1 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(372): call_user_func_array('ps_1760_copy_da...', Array)
#2 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(340): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...')
#3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(264): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...')
#4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(52): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.6.1.23')
#5 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.6.1.23')
#6 /var/www/html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#7 /var/www/html/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
#8 {main}
```

**Expected behavior**
No fatal error should be thrown

**Screenshots**

![Capture d’écran du 2019-04-18 17-13-02](https://user-images.githubusercontent.com/6768917/56375413-56a84800-61fd-11e9-9913-343655696c9b.png)

**Server (please complete the following information):**
 - Web Server: Apache
 - PHP Version: 7.1
 - Module Version 4.7.0

**Comment by Quetzacoalt91** [comment]
After initialization:

```
[2019-04-18 19:03:10] [INTERNAL] /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/CacheItem.php line 156 - Symfony\Component\Cache\Exception\InvalidArgumentException: Cache key must be string, "NULL" given
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/AbstractTrait.php(235): Symfony\Component\Cache\CacheItem::validateKey(NULL)
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Cache/Adapter/AbstractAdapter.php(152): Symfony\Component\Cache\Adapter\AbstractAdapter->getId(NULL)
#2 /var/www/html/src/Core/Localization/CLDR/DataLayer/LocaleCache.php(82): Symfony\Component\Cache\Adapter\AbstractAdapter->getItem(NULL)
#3 /var/www/html/src/Core/Data/Layer/AbstractDataLayer.php(90): PrestaShop\PrestaShop\Core\Localization\CLDR\DataLayer\LocaleCache->doRead(NULL)
#4 /var/www/html/src/Core/Localization/CLDR/LocaleDataSource.php(62): PrestaShop\PrestaShop\Core\Data\Layer\AbstractDataLayer->read(NULL)
#5 /var/www/html/src/Core/Localization/CLDR/LocaleRepository.php(60): PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleDataSource->getLocaleData(NULL)
#6 /var/www/html/classes/Currency.php(786): PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleRepository->getLocale(NULL)
#7 /var/www/html/admin-dev/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php(55): CurrencyCore->refreshLocalizedCurrencyData(Array, Object(PrestaShop\PrestaShop\Core\Localization\CLDR\LocaleRepository))
#8 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang()
#9 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(372): call_user_func_array('ps_1760_copy_da...', Array)
#10 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(340): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...')
#11 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(264): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...')
#12 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(55): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.6.1.23')
#13 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.6.1.23')
#14 /var/www/html/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#15 /var/www/html/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run()
#16 {main}
```

**Comment by Quetzacoalt91** [comment]
The locale is null, but the database has the expected data:

```
select * from ps_lang;
+---------+-------------------+--------+----------+---------------+------------------+------------------+--------+--------+
| id_lang | name              | active | iso_code | language_code | date_format_lite | date_format_full | is_rtl | locale |
+---------+-------------------+--------+----------+---------------+------------------+------------------+--------+--------+
|       1 | English (English) |      1 | en       | en-us         | m/d/Y            | m/d/Y H:i:s      |      0 | en-US  |
|       2 | Fran�ais (French) |      1 | fr       | fr-fr         | d/m/Y            | d/m/Y H:i:s      |      0 | fr-FR  |
+---------+-------------------+--------+----------+---------------+------------------+------------------+--------+--------+
2 rows in set (0.00 sec)

```

**Comment by langziyang** [comment]
1.7.5.2 upgrade to 1.7.6.0
`[INTERNAL] /var/www/demo.518global.com/admin1/autoupgrade/latest/install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php line 55 - Error: Call to a member function get() on null #0 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang() #1 /var/www/demo.518global.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(372): call_user_func_array('ps_1760_copy_da...', Array) #2 /var/www/demo.518global.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(340): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runPhpQuery('1.7.6.0', '/* PHP:ps_1760_...') #3 /var/www/demo.518global.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(264): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->runQuery('1.7.6.0', '/* PHP:ps_1760_...') #4 /var/www/demo.518global.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php(52): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->upgradeDb('1.7.5.2') #5 /var/www/demo.518global.com/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.5.2') #6 /var/www/demo.518global.com/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #7 /var/www/demo.518global.com/admin1/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #8 {main}`

**Comment by mathieuchateau** [comment]
I also have this bug when going to 1.7.6.0 :
`Aug  9 15:13:38 xxxxx php: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.ph
p:55#012Stack trace:#012#0 [internal function]: ps_1760_copy_data_from_currency_to_currency_lang()#012#1 src/PrestaShopBundle/Install/Upgrade.php(483): call_user_func_array('ps_1760_c
opy_da...', Array)#012#2 src/PrestaShopBundle/Install/Upgrade.php(826): PrestaShopBundle\Install\Upgrade->upgradeDb(Array)#012#3 install/upgrade/upgrade.php(89):
 PrestaShopBundle\Install\Upgrade->run()#012#4 {main}#012  thrown in install/upgrade/php/ps_1760_copy_data_from_currency_to_currency_lang.php on line 55
Aug  9 15:14:24 prd-sta-web01 php: PHP Warning:  Invalid argument supplied for foreach() in install/upgrade/php/ps1700_stores.php on line 35
`
