### ISSUE TITLE
Upgrade PS 1.6.1.23 > 1.7.5.1: "Duplicate entry '159-1' into ps_tab_lang table"

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/autoupgrade#301]
**Describe the bug**

When trying to update PrestaShop v1.6.1.23 to v1.7.5.1, files update is OK, database update until PS v.1.7.5.0 is OK but during 1.7.5.1 update an error occurred and stops upgrade.

**Upgrade environment**
 - Version you started from: 1.6.1.23
 - Version you upgrade to: 1.7.5.1
 - Way of upgrade: Web
 - Step concerned: upgrade DB v1.7.5.1
 - NO multishop and NO STOCK MANAGEMENT
 - Multilang : ID 1 FR - ID 2 EN

**Displayed log**
```
[OK] PHP 1.7.5.1 : \/* PHP:ps_1751_update_module_sf_tab(); *\/<\/div>"

"Updating database schema..."

[...]

"Executing: ALTER TABLE ps_tab_lang CHANGE name name VARCHAR(128) NOT NULL, ADD PRIMARY KEY (id_tab, id_lang)",

"11:02:37 ERROR [console] Error thrown while running command "prestashop:schema:update-without-foreign".

Message: "An exception occurred while executing 'ALTER TABLE ps_tab_lang CHANGE name name VARCHAR(128) NOT NULL, ADD PRIMARY KEY (id_tab, id_lang)':"

"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '159-1' for key 'PRIMARY'"

[	"exception" => Doctrine\DBAL\Exception\UniqueConstraintViolationException {\u2026},
	"command" => "prestashop:schema:update-without-foreign",
	"message" => "An exception occurred while executing 'ALTER TABLE ps_tab_lang CHANGE name name VARCHAR(128) NOT NULL, ADD PRIMARY KEY (id_tab, id_lang)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '159-1' for key 'PRIMARY' "
]

In AbstractMySQLDriver.php line 66
```

And here a screenshot of my _ps_tab_lang_, that showing 2 entry for "159-1":

![ps_tab_lang](https://user-images.githubusercontent.com/7419525/56726594-58b75d00-674f-11e9-9415-1784c03d1f2f.png)

Bellow a full SQL export of _ps_tab_lang_ table (.txt extension is to remove) 

[new_tab_lang.sql.txt](https://github.com/PrestaShop/autoupgrade/files/3116288/new_tab_lang.sql.txt)

**Expected behavior**

Finish successfully upgrade database to 1.7.5.1

**Screenshots**

![upgrade-failed](https://user-images.githubusercontent.com/7419525/56726437-00805b00-674f-11e9-9c6d-beaaf21872d4.png)

Failed in picture (NB: table prefix is "new_" in reality)

**Server**

 - Web Server:  Nginx
 - PHP Version: 5.6
 - Module Version: 4.7.0
 - PHPPSinfo:
![PHPPSinfo](https://user-images.githubusercontent.com/7419525/56727297-ae403980-6750-11e9-864a-1ea0ed9054f6.png)

**Comment by Quetzacoalt91** [comment]
Hi @Klemart3D,

Interesting edge case. At the moment I don't know if something should be added on the core side as you're the first person to warn us about this issue.

In the meantime, it looks like to have to clean your table a little bit. The last lines in the extract you sent us seem to be duplicates. Deleting the duplicates before trying again should fix your issue.

**Comment by Klemart3D** [comment]
Hi @Quetzacoalt91,
Thanks for your answer.
Before upgrade, my _ps_tab_lang_ is clean (the highest _id_tab_ is 111 and there is not duplicate).
I attach you [my original table before upgrade](https://github.com/PrestaShop/autoupgrade/files/3116561/new_tab_lang_before_upgrade.sql.txt)
I found another strangest thing during db update (into the table export of my initial post), the _id_tab_ for "Stock" tab is set to "0", just before the duplicated case:
![stock_id_tab](https://user-images.githubusercontent.com/7419525/56731655-4cd19800-675b-11e9-91af-f84bd1142dfa.png)

So that will can be the origin of problem. But I don't have enabled "Advanced Stock Management" into PS 1.6.
What is sure, it's only during upgrade that some tabs are added and duplicated.
I will retry upgrade and investigate more to find why.

**Comment by Quetzacoalt91** [comment]
Thanks for the clarification by adding a dump before upgrade.

I'll have a look on my side, but as I'm using a default environment this issue is unlikely to be reproduced.

**Comment by Klemart3D** [comment]
I retried another upgrade but still failed at the same point with the same error.
I found a 502 error on _AdminLogin_ controller during process:
![502-before-end-of-process](https://user-images.githubusercontent.com/7419525/56738556-24529980-676d-11e9-882f-56d0ac76593c.png)

**Comment by Quetzacoalt91** [comment]
You can safely ignore the redirect from ajax.php and the HTTP 502 on AdminLogin, as they are caused by the upgrade in progress.

Would you mind sharing all your new_tab* content before upgrade? This could help me reproducing the issue (just tried without success).

**Comment by Klemart3D** [comment]
Joined: [dump of new_tab* tables before upgrade](https://github.com/PrestaShop/autoupgrade/files/3117473/new_tab.sql.txt)

**Comment by Klemart3D** [comment]
Retried with a local archive of PS 1.7.5.0 (in place of 1.7.5.1) but same result:
![upgrade-v1750](https://user-images.githubusercontent.com/7419525/56748030-61c02280-677f-11e9-8f1b-5bb61c0a87f2.png)

**Comment by Klemart3D** [comment]
Trying with a local archive of PS 1.7.0.0 but failed:

![failed-to-1700](https://user-images.githubusercontent.com/7419525/56793565-9928e080-680c-11e9-8e5a-6da432f4ad09.png)

**Comment by Quetzacoalt91** [comment]
Hi there,

I reproduce the issue with your dump. Looks like the upgrade script does not handle properly your shop, which duplicates the tabs. I'll have a look later on this.

**Comment by Klemart3D** [comment]
Hi @Quetzacoalt91 ,
I need to finish my migration notwithstanding. Do you have a workaround or something I have to clean in my database to continue? Or will be better for me to install a fresh 1.7 version and upgrade data manually?

**Comment by Klemart3D** [comment]
I removed gamification module + all my custom module tabs from database, but still remain the problem.
It seems during each upgrade, all previous _ps_tab_lang_ are deleted and news PS17 tables are added, but after it creates the "More" table entry with right _id_tab_ auto-incremented, it creates a "Stock" entry but auto-increment failed and give an _id_tab_ to "0". After, and without I understanding why it will recreate an entry that already had been created in database, in my case: "149 - Modules" that creates the integrity constraint violation:

![tab-lang-error](https://user-images.githubusercontent.com/7419525/57127026-5aa4a000-6d8f-11e9-86d0-7959e515b4c2.png)

**Comment by Klemart3D** [comment]
I found why, it was a problem of primary key that wasn't exported in my database dump, so it don't came from a module problem. I restored the database from the initial dump and upgrade works fine.

**Comment by Quetzacoalt91** [comment]
Thanks for letting me know. I don't know if I can do something to prevent this kind of issue to happen later. Checking the current database against the original structure seems interesting but would require some time to be implemented.

**Comment by matks** [comment]
> Checking the current database against the original structure seems interesting but would require some time to be implemented.

Additionally it would generate false positive results for people who have extended their database structure through the use of modules 🤔 .

**Comment by Klemart3D** [comment]
@Quetzacoalt91 Yes a database check will can be a useful improve before an upgrade, it can be something like the ["check and Fix" of _ps_cleaner_ module (improperly named "check integrity")](https://github.com/PrestaShop/pscleaner/blob/master/pscleaner.php#LC137) but without adding/deleting data, just display an alert if are missing some required tables, columns or primary keys.

@matks Of course modules can extends database, but it always be possible to check the minimal database structure required by PrestShop to be functionnal, not necessarily the "exact" structure. I don't think a module have to change existing core tables structure or names...?

**Comment by Quetzacoalt91** [comment]
> Additionally it would generate false positive results for people who have extended their database structure through the use of modules thinking .

We ask module developers to NOT alter core table. We require them to create their own tables with a relation to the core.
