### ISSUE TITLE
Upgrade 1.6.1.19 to 1.6.1.24

### ISSUE THREAD

**Issue by SilvanScherrer** [PrestaShop/autoupgrade#310]
When i click on the 1-Click updrade I get the following:
 
Start your Upgrade

You come from the future! You are using a more recent version than the latest available!

Your current PrestaShop version: 1.6.1.19

Latest official version for minor channel.: N/A

**Upgrade environment (please complete the following information):**
 - Version you started from: [e.g. 1.6.1.19]
 - Version you upgrade to: [e.g. 1.6.1.24]
 - Way of upgrade: Web

**Expected behavior**
Showing latest version of 1.6, like 1.6.1.24

**Server (please complete the following information):**
 - Web Server: [Apache]
 - PHP Version: [5.6]
 - Module Version [4.7.0]

**Comment by Quetzacoalt91** [comment]
Interesting, have you already tried an upgrade before?

I'd like to know what is stored in your database. Can you please run: `select * from ps_configuration where name LIKE "%VERSION%";` ?

You should get the version installed on your server.
```
+------------------+---------------+---------+-------------------------+---------+---------------------+---------------------+
| id_configuration | id_shop_group | id_shop | name                    | value   | date_add            | date_upd            |
+------------------+---------------+---------+-------------------------+---------+---------------------+---------------------+
|                2 |          NULL |    NULL | PS_VERSION_DB           | 1.7.6.0 | 2019-04-10 18:07:59 | 2019-04-10 18:07:59 |
|                3 |          NULL |    NULL | PS_INSTALL_VERSION      | 1.7.6.0 | 2019-04-10 18:07:59 | 2019-04-10 18:07:59 |
+------------------+---------------+---------+-------------------------+---------+---------------------+---------------------+
```

**Comment by SilvanScherrer** [comment]
Yes I did a couple of upgrades in the past. And it worked.
See below the output of the select statement.

id_configuration 	id_shop_group 	id_shop 	name 	value 	date_add 	date_upd
229 			PS_VERSION_DB 	1.6.1.19 	0000-00-00 00:00:00 	0000-00-00 00:00:00
233 			PS_INSTALL_VERSION 	1.5.6.2 	0000-00-00 00:00:00 	0000-00-00 00:00:00
265 			PS_LAST_VERSION 	a:10:{s:4:"name";s:12:"1.6.0 stable";s:3:"num";s:7:"1.6.0.5";s:4:"link";s:37:"http://www.prestashop.com/en/download";s:3:"md5";s:32:"242c9c7c3537f1d0ba48795fb8e72b7a";s:11:"autoupgrade";i:1;s:18:"autoupgrade_module";i:1;s:24:"autoupgrade_last_version";s:5:"1.3.0";s:23:"autoupgrade_module_link";s:50:"http://www.prestashop.com/download/autoupgrade.zip";s:9:"changelog";s:0:"";s:4:"desc";s:0:"";} 	2014-03-03 19:19:01 	2014-03-20 19:33:39
266 			PS_LAST_VERSION_CHECK 	1527665850 	2014-03-03 19:19:01 	2018-05-30 09:37:30
308 			PS_CCCJS_VERSION 	30 	2014-03-21 12:09:18 	2018-07-17 23:11:04
309 			PS_CCCCSS_VERSION 	35 	2014-03-21 12:09:18 	2019-02-13 08:43:06
393 			PAYPAL_VERSION 	3.11.0 	2014-07-30 18:23:10 	2016-10-31 14:46:26
443 			PS_GAPI_VERSION 	30 	2016-09-19 18:56:18 	2016-09-19 18:56:18
467 			PAYPAL_VERSION_TLS_CHECKED 	1.2 	2016-10-31 13:22:22 	2016-10-31 13:22:22
468 			PAYPAL_VERSION_TLS_LAST_UPDATE 	20170316

**Comment by Quetzacoalt91** [comment]
Please check you're properly on the "Minor" channel when opening the "Expert mode", then click on "Check that a new version is available".

If this does not work, your server has probably some issues to get the last details from the API.

**Comment by SilvanScherrer** [comment]
Unfortunately this did not work either. Is there a way to debug the module? As I see no errors in any logs.

**Comment by Quetzacoalt91** [comment]
There is currently no such debug panel about the details loaded.
If you're confident in modifying the code, you may add a dump of the `$upgrader` variable in the `display()` method of the file `AdminSelfUpgrade.php`.


```php
    public function display()
    {

     [...]


        $this->ajax = true;
        $this->content = $this->_html;

        ppp($upgrader);

        return parent::display();
```

Some details should appear to let you know what is the current upgrade configuration.

**Comment by SilvanScherrer** [comment]
this issue is fixed. It was a cert issue with openssl.
