### ISSUE TITLE
Analytics problem

### ISSUE THREAD

**Issue by SergioDelia** [PrestaShop/autoupgrade#317]
Analytics module tracks Amazon orders too. How is it possible? I want to track only the orders in my site.

I'm using PS 1.6.1

**Comment by Quetzacoalt91** [comment]
Hi @SergioDelia,

I'm sorry but this is not the proper place to ask this question.
This repository is dedicated to issues related to the upgrade module itself. I recommend you to reach the developper of the analytics module instead.

Regards
