### ISSUE TITLE
Failure during upgrade on IIS (PS cache and other accelerator to be cleaned)

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/autoupgrade#82]
**Describe the bug**
Tested an upgrade on IIS to check everything is fine before a stable release of 4.0.0. --> **failed**

**Upgrade environment (please complete the following information):**
 - Version you started from: 1.7.1.0
 - Version you upgrade to: 1.7.3.3 (major channel)
 - Way of upgrade: Web
 - Step concerned: upgrade DB

**Displayed log**
```
[INTERNAL] C:\inetpub\wwwroot\ps\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Bundle\Bundle.php line 199 - ReflectionException: Class PrestaShopBundle\Command\UpdateLicencesCommand does not exist 
#0 C:\inetpub\wwwroot\ps\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Bundle\Bundle.php(199): ReflectionClass->__construct('PrestaShopBundl...') 
#1 C:\inetpub\wwwroot\ps\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(140): Symfony\Component\HttpKernel\Bundle\Bundle->registerCommands(Object(Symfony\Bundle\FrameworkBundle\Console\Application)) 
#2 C:\inetpub\wwwroot\ps\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(121): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() 
#3 C:\inetpub\wwwroot\ps\src\PrestaShopBundle\Service\Database\Upgrade.php(39): Symfony\Bundle\FrameworkBundle\Console\Application->add(Object(PrestaShopBundle\Command\UpdateSchemaCommand)) 
#4 C:\inetpub\wwwroot\ps\modules\autoupgrade\classes\UpgradeTools\SymfonyAdapter.php(74): PrestaShopBundle\Service\Database\Upgrade->addDoctrineSchemaUpdate() 
#5 C:\inetpub\wwwroot\ps\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader17.php(59): PrestaShop\Module\AutoUpgrade\UpgradeTools\SymfonyAdapter->runSchemaUpgradeCommand() 
#6 C:\inetpub\wwwroot\ps\modules\autoupgrade\classes\UpgradeTools\CoreUpgrader\CoreUpgrader.php(81): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader17->upgradeDb('1.7.1.0') 
#7 C:\inetpub\wwwroot\ps\modules\autoupgrade\classes\TaskRunner\Upgrade\UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() 
#8 C:\inetpub\wwwroot\ps\trololo\autoupgrade\ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() 
#9 {main}
```

**Expected behavior**
Clearing the cache uses the proper command depending on the running version of PrestaShop. The class is likely existing and we rely on the core to clear the cache, so I guess there is an issue with an autoloader cache.

**Server (please complete the following information):**
 - Web Server: IIS
 - PHP Version: 7.0.14
 - Module Version 4.0.0-beta.1

**Additional context**
I already had this issue, it was an issue with the classes cache which wasn't properly refreshed.

**Comment by Quetzacoalt91** [comment]
The issue does not occur anymore on the future v4.8.0, so it can be closed. This is likely thanks to the PR https://github.com/PrestaShop/autoupgrade/pull/306 which removes the cache before running the step UpgradeDB (which was crashing in the original message).

**Comment by matks** [comment]
@Quetzacoalt91 Do we support officially IIS then ?

**Comment by Quetzacoalt91** [comment]
Of course we are: https://www.prestashop.com/en/system-requirements

**Comment by matks** [comment]
Then we should dedicate it some place in the QA process. Currently I dont think extensive testing is done on IIS, neither on XAMPP.

As this will require a lot more time and energy, I would be in favor of a un-official support. "We think it works, but no guarantee". But this will require to update this webpage indeed.
