### ISSUE TITLE
Updating database schema...  1.6.1.7 --> 1.7.3.3

### ISSUE THREAD

**Issue by PrestaHeroes** [PrestaShop/autoupgrade#87]
Hi, I keep running into this issue at upgrade:

SOLVED:  I exported the mysql structure and one  of our modules has table 'bit', I modified and was able to complete db upgrade.  thanks, Fred

Updating database schema...
[Doctrine\DBAL\DBALException]
Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
prestashop:schema:update-without-foreign [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--id_shop [ID_SHOP]] [--id_shop_group [ID_SHOP_GROUP]] [--]

I even upgraded my hosting as old dedicated was from 2014 and  older mysql.  No love.

Please let me know if any advice on upgrading.  Note: we have been testing autoupgrade and worked fine on 3 other 'saved' old client 1.6 shops. 

1-Click Upgrade v4.0.0 - by PrestaShop
Server information Linux #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64

Server software version Apache
PHP version 5.6.36
Memory limit 512M
Max execution time 600
MySQL version 5.5.56-MariaDB
MySQL server localhost
MySQL name phcom1733_06232018
MySQL user phcom1733_0623
Tables prefix etiendasco_
MySQL engine InoDB
MySQL driver DbPDO

Thank you, Fred

**Comment by Quetzacoalt91** [comment]
Hi @PrestaHeroes,

Never heard of that issue yet, I guess you're the only to get it for now.
By looking for this error, it seems there's a solution to prevent it to occur: https://stackoverflow.com/a/23794964
You can try it, then re-execute the database upgrade by executing in a terminal the following command:

```bash
php app/console prestashop:schema:update-without-foreign
```

**Comment by PrestaHeroes** [comment]
Hi, thanks for fast feedback.  I solved by exporting the mysql db structure, then searched on 'bit'.  There was 3rd party module so I changed to tinyurl and db upgrade was successful.  Please close.  We will continue our testing but are very excited to see autouprade for pre to 1.7....Cheers, Fred

**Comment by Quetzacoalt91** [comment]
Awesome, thanks for your feedback too. We expected to see more and more details on the occurring issues, which is finally happening. :raised_hands:

**Comment by joseabellan84** [comment]
I have the same problem. What type of data do you recommend you use to replace the bit type?

**Comment by Quetzacoalt91** [comment]
Depending on the needs, this could be `TINYINT(1)`
